<a href="https://colab.research.google.com/github/byuruth/Econ484/blob/main/pset3coding_ruthwright.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Problem Set 3

Many of the concepts needed to complete this homework are introduced in the recitation notebooks and the python tutorials.

In [ ]:
# Import the packages and libraries you will use here
from pandas.plotting import scatter_matrix
import seaborn
import pandas as pd
from matplotlib import pyplot as plt

### 1
This exercise relates to the College data set, which can be found in the file College.csv. It contains a number of variables for 777 different universities and colleges in the US. The variables are  
* Private : Public/private indicator  
* Apps : Number of applications received  
* Accept : Number of applicants accepted  
* Enroll : Number of new students enrolled  
* Top10perc : New students from top 10 % of high school class  
* Top25perc : New students from top 25 % of high school class  
* F.Undergrad : Number of full-time undergraduates
* P.Undergrad : Number of part-time undergraduates  
* Outstate : Out-of-state tuition  
* Room.Board : Room and board costs  
* Books : Estimated book costs  
* Personal : Estimated personal spending  
* PhD : Percent of faculty with Ph.D.’s  
* Terminal : Percent of faculty with terminal degree  
* S.F.Ratio : Student/faculty ratio  
* perc.alumni : Percent of alumni who donate  
* Expend : Instructional expenditure per student  
* Grad.Rate : Graduation rate  
Before reading the data into python, it can be viewed in Excel or a text editor is well.

### (a)
Use the pandas read_csv() function to read the data into python. Call the loaded data df. Make sure that you have the directory set to the correct location for the data or use the absolute filepath so the program knows where to look for the file. Use `head` and `tail` to show the first 10 and last 10 observations of the data,the default is five so you will need to add an argument for the number of rows.

In [ ]:
!git clone https://github.com/byuruth/Econ484.git
%cd Econ484/data
df = pd.read_csv('College.csv')
df.head(10)
df.tail(10)

Cloning into 'Econ484'...
remote: Enumerating objects: 114, done.
remote: Counting objects: 100% (114/114), done.
remote: Compressing objects: 100% (111/111), done.
remote: Total 114 (delta 34), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (114/114), 10.80 MiB | 4.74 MiB/s, done.
Resolving deltas: 100% (34/34), done.
/content/Econ484/data/Econ484/data/Econ484/data/Econ484/data/Econ484/data/Econ484/data/Econ484/data

,Unnamed: 0,Private,Apps,Accept,Enroll,Top10perc,Top25perc,F.Undergrad,P.Undergrad,Outstate,Room.Board,Books,Personal,PhD,Terminal,S.F.Ratio,perc.alumni,Expend,Grad.Rate
767,Winthrop University,No,2320,1805,769,24,61,3395,670,6400,3392,580,2150,71,80,12.8,26,6729,59
768,Wisconsin Lutheran College,Yes,152,128,75,17,41,282,22,9100,3700,500,1400,48,48,8.5,26,8960,50
769,Wittenberg University,Yes,1979,1739,575,42,68,1980,144,15948,4404,400,800,82,95,12.8,29,10414,78
770,Wofford College,Yes,1501,935,273,51,83,1059,34,12680,4150,605,1440,91,92,15.3,42,7875,75
771,Worcester Polytechnic Institute,Yes,2768,2314,682,49,86,2802,86,15884,5370,530,730,92,94,15.2,34,10774,82
772,Worcester State College,No,2197,1515,543,4,26,3089,2029,6797,3900,500,1200,60,60,21.0,14,4469,40
773,Xavier University,Yes,1959,1805,695,24,47,2849,1107,11520,4960,600,1250,73,75,13.3,31,9189,83
774,Xavier University of Louisiana,Yes,2097,1915,695,34,61,2793,166,6900,4200,617,781,67,75,14.4,20,8323,49
775,Yale University,Yes,10705,2453,1317,95,99,5217,83,19840,6510,630,2115,96,96,5.8,49,40386,99
776,York College of Pennsylvania,Yes,2989,1855,691,28,63,2988,1726,4990,3560,500,1250,75,75,18.1,28,4509,99

### (b)
Read in the data again this time calling the data college and using the parameter index_col=0 in the read_csv function. Notice the difference between the index used when the dataframe is displayed.

In [ ]:
college = pd.read_csv('College.csv',index_col=0)
college

,Private,Apps,Accept,Enroll,Top10perc,Top25perc,F.Undergrad,P.Undergrad,Outstate,Room.Board,Books,Personal,PhD,Terminal,S.F.Ratio,perc.alumni,Expend,Grad.Rate
Abilene Christian University,Yes,1660,1232,721,23,52,2885,537,7440,3300,450,2200,70,78,18.1,12,7041,60
Adelphi University,Yes,2186,1924,512,16,29,2683,1227,12280,6450,750,1500,29,30,12.2,16,10527,56
Adrian College,Yes,1428,1097,336,22,50,1036,99,11250,3750,400,1165,53,66,12.9,30,8735,54
Agnes Scott College,Yes,417,349,137,60,89,510,63,12960,5450,450,875,92,97,7.7,37,19016,59
Alaska Pacific University,Yes,193,146,55,16,44,249,869,7560,4120,800,1500,76,72,11.9,2,10922,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Worcester State College,No,2197,1515,543,4,26,3089,2029,6797,3900,500,1200,60,60,21.0,14,4469,40
Xavier University,Yes,1959,1805,695,24,47,2849,1107,11520,4960,600,1250,73,75,13.3,31,9189,83
Xavier University of Louisiana,Yes,2097,1915,695,34,61,2793,166,6900,4200,617,781,67,75,14.4,20,8323,49
Yale University,Yes,10705,2453,1317,95,99,5217,83,19840,6510,630,2115,96,96,5.8,49,40386,99
York College of Pennsylvania,Yes,2989,1855,691,28,63,2988,1726,4990,3560,500,1250,75,75,18.1,28,4509,99

### (c)
Now we will do some prelimainary analysis and visualizations of the data that was loaded  
$\mathbf{i)}$ Use the describe method of the dataframe object that you made by reading in the data to show the summary statistics of each of the columns

<bound method DataFrame.sum of                                Private   Apps  Accept  Enroll  Top10perc  \
Abilene Christian University       Yes   1660    1232     721         23
Adelphi University                 Yes   2186    1924     512         16
Adrian College                     Yes   1428    1097     336         22
Agnes Scott College                Yes    417     349     137         60
Alaska Pacific University          Yes    193     146      55         16
...                                ...    ...     ...     ...        ...
Worcester State College             No   2197    1515     543          4
Xavier University                  Yes   1959    1805     695         24
Xavier University of Louisiana     Yes   2097    1915     695         34
Yale University                    Yes  10705    2453    1317         95
York College of Pennsylvania       Yes   2989    1855     691         28

                                Top25perc  F.Undergrad  P.Undergrad  Outstate  \
Abilene Christian University           52         2885          537      7440
Adelphi University                     29         2683         1227     12280
Adrian College                         50         1036           99     11250
Agnes Scott College                    89          510           63     12960
Alaska Pacific University              44          249          869      7560
...                                   ...          ...          ...       ...
Worcester State College                26         3089         2029      6797
Xavier University                      47         2849         1107     11520
Xavier University of Louisiana         61         2793          166      6900
Yale University                        99         5217           83     19840
York College of Pennsylvania           63         2988         1726      4990

                                Room.Board  Books  Personal  PhD  Terminal  \
Abilene Christian University          3300    450      2200   70        78
Adelphi University                    6450    750      1500   29        30
Adrian College                        3750    400      1165   53        66
Agnes Scott College                   5450    450       875   92        97
Alaska Pacific University             4120    800      1500   76        72
...                                    ...    ...       ...  ...       ...
Worcester State College               3900    500      1200   60        60
Xavier University                     4960    600      1250   73        75
Xavier University of Louisiana        4200    617       781   67        75
Yale University                       6510    630      2115   96        96
York College of Pennsylvania          3560    500      1250   75        75

                                S.F.Ratio  perc.alumni  Expend  Grad.Rate
Abilene Christian University         18.1           12    7041         60
Adelphi University                   12.2           16   10527         56
Adrian College                       12.9           30    8735         54
Agnes Scott College                   7.7           37   19016         59
Alaska Pacific University            11.9            2   10922         15
...                                   ...          ...     ...        ...
Worcester State College              21.0           14    4469         40
Xavier University                    13.3           31    9189         83
Xavier University of Louisiana       14.4           20    8323         49
Yale University                       5.8           49   40386         99
York College of Pennsylvania         18.1           28    4509         99

[777 rows x 18 columns]>

$\mathbf{ii)}$ Use the scatter_matrix function that was imported from pandas to produce scatter plots of the pairwise combinations of 6 of the variables of your choice. Adjust the figsize argument make the displayed plots more readable and understandable.

In [ ]:


# call the function above these lines
plt.tight_layout() # this makes the output a little neater when you display plots
plt.show() # this will force the plots to show, they only show without this if they are the output of the last line in a cell

$\mathbf{iii)}$ Use seaborn's or matplotlib's boxplot function to create a boxplot of Outstate on private.  
Hint: You can either pass in the columns as objects or the names of the columns and use data=college as a parameter

$\mathbf{iv)}$  Create a new qualitative variable in the dataframe, called Elite, by binning the Top10perc variable. We are going to divide universities into two groups based on whether or not the number of students coming from the top 10% of their high school classes exceeds 50.

Get a count of how many universities are in the 'Elite' category. Now make boxplot of Outstate on Elite.

$\mathbf{v)}$ Use seaborn's distplot function to produce some histograms with differing numbers of bins for a quantitative variable of your choice. You can make multiple cells or if you are familiar with python try making a grid of multiple plots to be displayed by one cell.

You can create a grid of histograms with the hist method of the dataframe. Choose some variables that seem interesting and create histograms in this way.

Using the tools that were introduced and/or other ones you find, continue exploring the data set and write a brief summary of what you find. This should involve something you do that was not a part of the previous responses.  
We are not looking for anything in particular just try to make something that shows something about the data ond its relationships in graphs or summary statistics that you haven't already created above.

Explain what you did and what it means here

## Chapter 3
$\mathbf{a)}$Load in auto.csv as a dataframe and the produce a grid of the pairwise scatterplots of the variables of the dataframe

$\mathbf{b)}$ Show the correlation matrix. There are several ways to do this but you should be able to find a function that makes it for the numeric variables of a dataframe.

$\mathbf{c)}$ Use the statsmodel OLS function to perform a linear regression with mpg as the response and year as a feature (a variable in the regression). Use the summary() method to print the results.

In [ ]:
# fill in the variable names you plan on using in the regression
X = auto.loc[:,['x1','x2','x3']]
y = auto['y']
reg_obj = sm.OLS(y,X)
results = reg_obj.fit()
print(results.summary())

Do a linear regression with mpg as the outcome and all other variables except name as the predictors. Comment on the output. For instance:  
i. Is there a relationship between the predictors and the response?  
ii. Which predictors appear to have a statistically significant relationship to the response?  
iii. What does the coefficient for the year variable suggest?

## Supervised Machine Learning
In this problem, you will develop a model to predict whether a given car gets high or low gas mileage based on the `Auto` data set. you should be able to use the same dataframe for the previous problem using the auto dataset here as well or you can load it in and start over if you want to practice

Calling the functions is similar for all of the functions from sklearn. This is one of the really nice things about the library: if you know how to use one then you know how to use them all. You will be asked to use models we have not deeply discussed in lecture but that will not change the coding aspect of it so you should be able to complete the assignment without knowing what exactly is happening. This is just meant to introduce you to how to use models from scikit-learn so don't worry if this is the case. This is one of the problems with the way a lot of people try to use machine learning so I do not recommend it in the future as predictions from a model you don't understand are probably not very good predictions no matter how good the scoring metrics do.

In [ ]:
# this creates a variable named mpg01 that indicates whetehr or not gas mileage iss above the median of the sample
auto['mpg01'] = auto['mpg'] > auto['mpg'].median()

Scikit-learn is set up so that if you know how to use one model you know how to use them all. Here is an example of the steps that you will follow in general for classification, like in the following question. A regression problem is with a continuous outcome and classification is with a discrete outcome.
```python
from sklearn.submoodule import Model # import a model from the appropriate submodule of scikit-learn
model_obj = Model() # create a model object with relevant tuning parameters
model_obj.fit(X, y) # fit the model to your data
model_obj.score(X, y) # get a score of how well the model does using a loss function
```

$(a)$ Create an X matrix and a Y vector. The variable you created called `mpg01` will be the y variable.  
Are there any variables that should not be included? Hint: I am aking this because there is a variable that should not be included.

$(b)$ Perform LogisticRegression on the training data in order to predict `mpg01`. How accurate is the model?

$(c)$ Perform DecisionTreeClassifier on the training data in order to predict `mpg01`. How accurate is the model?

$(d)$ Now run a random forest classifier on the data. If you are feeling comfortable with this, you can try different parameters to try and tune the model to give better results. This is not necessary to receive full credit.